/*
Author: Hidalgo
Date: 19/02/21
 */
package PKHidalgo;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class JFrameMain_Piano extends javax.swing.JFrame {

    String[] notas = {"DoSharp", "ReSharp", "FaSharp", "SolSharp", "LaSharp", "DoSharp2", "ReSharp2", "FaSharp2", "SolSharp2", "LaSharp2", "Do", "Re", "Mi", "Fa", "Sol", "La", "Si", "Do2", "Re2", "Mi2", "Fa2", "Sol2", "La2", "Si2"};
    JButton[] jb;
    int contador = 0;

    public JFrameMain_Piano() {
        initComponents();
        initConfig();
        keyboardlistener();
        initArrays();
    }
    
    private void initArrays(){
        //String[] notas = {"DoSharp", "ReSharp", "FaSharp", "SolSharp", "LaSharp", "DoSharp2", "ReSharp2", "FaSharp2", "SolSharp2", "LaSharp2", "Do", "Re", "Mi", "Fa", "Sol", "La", "Si", "Do2", "Re2", "Mi2", "Fa2", "Sol2", "La2", "Si2"};
        jb = new JButton[]{jButtonDoNegra,jButtonReNegra,jButtonFaNegra,jButtonSolNegra,jButtonLaNegra,jButtonDobNegra,jButtonRebNegra,jButtonFabNegra,jButtonSolbNegra,jButtonLabNegra,jButtonDo,jButtonRe,jButtonMi,jButtonFa,jButtonSol,jButtonLa,jButtonSi,jButtonDo2,jButtonRe2,jButtonMi2,jButtonFa2,jButtonSol2,jButtonLa2,jButtonSi2};
        for(int i=0; i<jb.length; i++){
            jb[i].setName(""+i);
        }
    }

    private void initConfig() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screen.getWidth() * 60 / 100;
        int height = (int) screen.getHeight() * 60 / 100;
        this.setSize(width, height);
        this.setLocationRelativeTo(this);
        this.getContentPane().setBackground(Color.WHITE);
    }

    //en el constructor llamar al método keyboardlistener();
//el listener del teclado
    private void keyboardlistener() {
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(final KeyEvent e) {
                synchronized (JFrame.class) {
                    readKeyBoard(e);
                    return false;
                }
            }
        });
    }
//gestión de la Tecla apretada:

    public void readKeyBoard(KeyEvent event) {
        
        String teclas = "QWERTYUIOPASDFGHJKLÑZXCV";

        try {
            contador++;
            char letter = event.getKeyChar();
            int index = teclas.indexOf(letter);
            if (contador % 3 == 0) {
                //JOptionPane.showMessageDialog(this, letter + " : " + index + " : " + notas[index]);
                //sound(notas[index]);
                jb[index].doClick();
            }
        } catch (Exception e) {
        }
    }

    private void sound(String nota) {
        String separator = File.separator;
        String sNota = "Sounds/" + nota + ".wav";
        System.out.println(sNota);
        AudioClip audioClip;
        audioClip = java.applet.Applet.newAudioClip(getClass().getResource(sNota));
        audioClip.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDoNegra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonReNegra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonFaNegra = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonSolNegra = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonLaNegra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonDobNegra = new javax.swing.JButton();
        jButtonRebNegra = new javax.swing.JButton();
        jButtonFabNegra = new javax.swing.JButton();
        jButtonSolbNegra = new javax.swing.JButton();
        jButtonLabNegra = new javax.swing.JButton();
        jButtonDo = new javax.swing.JButton();
        jButtonRe = new javax.swing.JButton();
        jButtonMi = new javax.swing.JButton();
        jButtonFa = new javax.swing.JButton();
        jButtonSol = new javax.swing.JButton();
        jButtonLa = new javax.swing.JButton();
        jButtonSi = new javax.swing.JButton();
        jButtonDo2 = new javax.swing.JButton();
        jButtonRe2 = new javax.swing.JButton();
        jButtonMi2 = new javax.swing.JButton();
        jButtonFa2 = new javax.swing.JButton();
        jButtonSol2 = new javax.swing.JButton();
        jButtonLa2 = new javax.swing.JButton();
        jButtonSi2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonPause = new javax.swing.JButton();
        jButtonMute = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DO#");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 110, 30, 30);

        jButtonDoNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDoNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDoNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDoNegra);
        jButtonDoNegra.setBounds(40, 20, 40, 130);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RE#");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 110, 30, 30);

        jButtonReNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonReNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReNegra);
        jButtonReNegra.setBounds(90, 20, 40, 130);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FA#");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 110, 30, 30);

        jButtonFaNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFaNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonFaNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFaNegra);
        jButtonFaNegra.setBounds(190, 20, 40, 130);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SOL#");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 110, 40, 30);

        jButtonSolNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSolNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSolNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSolNegra);
        jButtonSolNegra.setBounds(240, 20, 40, 130);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LA#");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 110, 30, 30);

        jButtonLaNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLaNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonLaNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLaNegra);
        jButtonLaNegra.setBounds(290, 20, 40, 130);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DOb");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 110, 30, 30);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REb");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 110, 30, 30);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FAb");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 110, 30, 30);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SOLb");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 110, 40, 30);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lab");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(650, 110, 30, 30);

        jButtonDobNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDobNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDobNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDobNegra);
        jButtonDobNegra.setBounds(390, 20, 40, 130);

        jButtonRebNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRebNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonRebNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRebNegra);
        jButtonRebNegra.setBounds(440, 20, 40, 130);

        jButtonFabNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFabNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonFabNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFabNegra);
        jButtonFabNegra.setBounds(540, 20, 40, 130);

        jButtonSolbNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSolbNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSolbNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSolbNegra);
        jButtonSolbNegra.setBounds(590, 20, 40, 130);

        jButtonLabNegra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLabNegra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonLabNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLabNegra);
        jButtonLabNegra.setBounds(640, 20, 40, 130);

        jButtonDo.setText("Do");
        jButtonDo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonDo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonDoFocusGained(evt);
            }
        });
        jButtonDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDoMouseExited(evt);
            }
        });
        jButtonDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDo);
        jButtonDo.setBounds(10, 20, 50, 210);

        jButtonRe.setText("Re");
        jButtonRe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReMouseExited(evt);
            }
        });
        jButtonRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRe);
        jButtonRe.setBounds(60, 20, 50, 210);

        jButtonMi.setText("Mi");
        jButtonMi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonMi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMiMouseExited(evt);
            }
        });
        jButtonMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMi);
        jButtonMi.setBounds(110, 20, 50, 210);

        jButtonFa.setText("Fa");
        jButtonFa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonFa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonFaMouseExited(evt);
            }
        });
        jButtonFa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFa);
        jButtonFa.setBounds(160, 20, 50, 210);

        jButtonSol.setText("Sol");
        jButtonSol.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSol);
        jButtonSol.setBounds(210, 20, 50, 210);

        jButtonLa.setText("La");
        jButtonLa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonLa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLa);
        jButtonLa.setBounds(260, 20, 50, 210);

        jButtonSi.setText("Si");
        jButtonSi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSi);
        jButtonSi.setBounds(310, 20, 50, 210);

        jButtonDo2.setText("Do'");
        jButtonDo2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonDo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDo2);
        jButtonDo2.setBounds(360, 20, 50, 210);

        jButtonRe2.setText("Re'");
        jButtonRe2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonRe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRe2);
        jButtonRe2.setBounds(410, 20, 50, 210);

        jButtonMi2.setText("Mi'");
        jButtonMi2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonMi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMi2);
        jButtonMi2.setBounds(460, 20, 50, 210);

        jButtonFa2.setText("Fa'");
        jButtonFa2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonFa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFa2);
        jButtonFa2.setBounds(510, 20, 50, 210);

        jButtonSol2.setText("Sol'");
        jButtonSol2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonSol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSol2);
        jButtonSol2.setBounds(560, 20, 50, 210);

        jButtonLa2.setText("La'");
        jButtonLa2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonLa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLa2);
        jButtonLa2.setBounds(610, 20, 50, 210);

        jButtonSi2.setText("Si'");
        jButtonSi2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonSi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSi2);
        jButtonSi2.setBounds(660, 20, 50, 210);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Do");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 110, 20, 14);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jButton7);
        jButton7.setBounds(40, 20, 40, 130);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jButton8);
        jButton8.setBounds(90, 20, 40, 130);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jButton9);
        jButton9.setBounds(190, 20, 40, 130);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jButton16);
        jButton16.setBounds(240, 20, 40, 130);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jButton17);
        jButton17.setBounds(290, 20, 40, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 150, 730, 260);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/5a02cb3018e87004f1ca43e5.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(560, 30, 50, 110);

        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/pause-button.png"))); // NOI18N
        getContentPane().add(jButtonPause);
        jButtonPause.setBounds(360, 80, 80, 60);

        jButtonMute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/27150.png"))); // NOI18N
        getContentPane().add(jButtonMute);
        jButtonMute.setBounds(360, 10, 80, 60);

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/375.png"))); // NOI18N
        getContentPane().add(jButtonStart);
        jButtonStart.setBounds(450, 80, 80, 60);

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/Stop-Music-icon.png"))); // NOI18N
        getContentPane().add(jButtonStop);
        jButtonStop.setBounds(270, 80, 80, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/5a02cb3018e87004f1ca43e5.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 30, 50, 110);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/Imagen1.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 10, 80, 84);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKHidalgo/Images/Sin título.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 110, 160, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Melodia2");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(670, 60, 120, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Melodia1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(670, 20, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoActionPerformed
        int index=Integer.parseInt(((JButton)evt.getSource()).getName());
        sound(notas[index]);
    }//GEN-LAST:event_jButtonDoActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        AudioClip audioClip;
        audioClip = java.applet.Applet.newAudioClip(getClass().getResource("Sounds/alegria.wav"));
        if(jRadioButton2.isSelected()){
        audioClip.play();
        }else{
            audioClip.stop();
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        AudioClip audioClip;
        audioClip = java.applet.Applet.newAudioClip(getClass().getResource("Sounds/Elisa.wav"));
        if(jRadioButton1.isSelected()){
        audioClip.play();
        }else{
            audioClip.stop();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonDoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonDoFocusGained
        
    }//GEN-LAST:event_jButtonDoFocusGained

    private void jButtonDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDoMouseClicked
        jButtonDo.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonDoMouseClicked

    private void jButtonDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDoMouseExited
        jButtonDo.setBackground(Color.white);
    }//GEN-LAST:event_jButtonDoMouseExited

    private void jButtonReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReMouseClicked
        jButtonRe.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonReMouseClicked

    private void jButtonReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReMouseExited
        jButtonRe.setBackground(Color.white);
    }//GEN-LAST:event_jButtonReMouseExited

    private void jButtonMiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiMouseClicked
        jButtonMi.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonMiMouseClicked

    private void jButtonMiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiMouseExited
        jButtonMi.setBackground(Color.white);
    }//GEN-LAST:event_jButtonMiMouseExited

    private void jButtonFaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFaMouseClicked
        jButtonFa.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonFaMouseClicked

    private void jButtonFaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFaMouseExited
        jButtonFa.setBackground(Color.white);
    }//GEN-LAST:event_jButtonFaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain_Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain_Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain_Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain_Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain_Piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDo;
    private javax.swing.JButton jButtonDo2;
    private javax.swing.JButton jButtonDoNegra;
    private javax.swing.JButton jButtonDobNegra;
    private javax.swing.JButton jButtonFa;
    private javax.swing.JButton jButtonFa2;
    private javax.swing.JButton jButtonFaNegra;
    private javax.swing.JButton jButtonFabNegra;
    private javax.swing.JButton jButtonLa;
    private javax.swing.JButton jButtonLa2;
    private javax.swing.JButton jButtonLaNegra;
    private javax.swing.JButton jButtonLabNegra;
    private javax.swing.JButton jButtonMi;
    private javax.swing.JButton jButtonMi2;
    private javax.swing.JButton jButtonMute;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonRe;
    private javax.swing.JButton jButtonRe2;
    private javax.swing.JButton jButtonReNegra;
    private javax.swing.JButton jButtonRebNegra;
    private javax.swing.JButton jButtonSi;
    private javax.swing.JButton jButtonSi2;
    private javax.swing.JButton jButtonSol;
    private javax.swing.JButton jButtonSol2;
    private javax.swing.JButton jButtonSolNegra;
    private javax.swing.JButton jButtonSolbNegra;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
